### ISSUE TITLE
04-mengen-04 erfordert Kenntnis von ^ und $

### ISSUE THREAD

**Issue by quassy** [CoderDojoPotsdam/regex-tutorial#12]
Der Abschnitt 4.4 setzt zum korrekten Lösen drei der unten gelisteten Aufgaben die Kenntnis von ^ (Anfang) und $ (Ende), oder alternativ \b (Word Break). Anfang und Ende werden aber erst in Kapitel 7 behandelt.

```
a10
a10
ba1
```

**Comment by niccokunzmann** [comment]
@quassy Danke für den Hinweis! Ich habe eine Pull-Request erstellt. #15 Magst du die mergen?
