### ISSUE TITLE
Multiple languages / translations

### ISSUE THREAD

**Issue by quassy** [CoderDojoPotsdam/regex-tutorial#13]
The tutorial should be available in multiple languages / allow for translations to be made, especially English.

**Comment by niccokunzmann** [comment]
@quassy There are several ways to create tranlations:

- JavaScript
- Copy&Paste the tutorial (add -de or -en in the end)
- jekyll (I worked on https://github.com/Stonelinks/jekyll-gettext-plugin but there are others )

What do you think? Sometimes, even the quizzes and expressions may change.

**Comment by quassy** [comment]
Not sure, at first glance none of the translation tools for Jekyll have convinced me. But I definitely think it should be a dedicated, native tool and neither JavaScript nor Copy&Paste, which both seem even worse to maintain.

**Comment by niccokunzmann** [comment]
I changed the type of the class="playfield". Now it provides a regular expression as reference. This way, the text in the listings can be changed by translations (i.e. automatic translations by google chrome) and the site still works.

**Comment by niccokunzmann** [comment]
Let's think from an other prespective: How would we write the code that should be translated?

If we use the Jekyll-Plugin, 01-buchstaben-03.html looks like this:

```
---
layout: exercise
translate:
  title: Buchstaben
---
<p>
  {{ translate In diesem Quiz ist der reguläre Ausdruck <span class="regex">N</span>.
  Für jede Zeile kannst du dich entscheiden, ob er in ihr zu finden ist
  oder nicht. }}
</p>
<div class="quiz">
  <div class="expression">{{ translate N }}</div>
  <ul class="choices">
    <li>{{ transtale Nase }}</li>
    <li>{{ translate Ananas }}</li>
    <li>{{ translate ANNA }}</li>
  </ul>
</div>
```
What do other options look like?

**Comment by quassy** [comment]
On second thought I think it would be wise to use a plugin-free version so we can keep the GitHub (Pages) workflow (only the [included plugins](https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb) can be used) and other people can contribute easily without someone having to rebuild manually. So **Copy&Paste** ;)

[Making Jekyll multilingual](https://www.sylvaindurand.org/making-jekyll-multilingual/) looks like a nice, plugin-free approach, even though I would use directories instead of the lang attribute (might still be necessary), so it looks like this (the `tutorial` directory is redudant anyway): 

```
https://coderdojopotsdam.github.io/regex-tutorial/de/00-einfuehrung-01
https://coderdojopotsdam.github.io/regex-tutorial/en/00-introduction-01
https://coderdojopotsdam.github.io/regex-tutorial/es/00-introducción-01
```

Unless someone writes a tool this means there would be no automated way to mark outdated translations, on the other hand files could keep the same straight-forward syntax and would be more flexible so different languages can have slightly different challenges.

**Comment by niccokunzmann** [comment]
Currently, the "tutorial" directory is used to determine which files belong to the tutorial [in _layouts/excercise.html line 35](https://github.com/CoderDojoPotsdam/regex-tutorial/blob/master/_layouts/exercise.html#L35).
But that can be changed.

How about this:
- we create a branch/folder/file with the first excercise
- translate it to English and German (and maybe an other language)

Then, we can see what it looks like, find the best structure and duplicate the structure to the other excercises.
@quassy Would you like to work on this together?

**Comment by niccokunzmann** [comment]
@quassy I pushed something to [the translations branch](https://github.com/CoderDojoPotsdam/regex-tutorial/tree/translation/translations) You can change it or discard it. We can also change the file names from `01-einfuehrung-02` to `01-01-einfuerung` or just make it blog posts. `0001-01-01-einfuerung.html`
What would your ideal structure look like?

Here are requirements by me:

- the folder should be sorted like the tutorial
- translated steps should be shown together

**Comment by niccokunzmann** [comment]
@quassy After I slept over it: please have a look at [branch translation-2](https://github.com/CoderDojoPotsdam/regex-tutorial/tree/translation-2/steps). Do you have ideas/objections?

**Comment by niccokunzmann** [comment]
Opened other issues to update the translations.

#21 is merged
