### ISSUE TITLE
Create favicon

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/regex-tutorial#17]
Website-link: https://coderdojopotsdam.github.io/regex-tutorial

## Expected Behavior

I would like to see a favicon in the browser menu.

## Actual Behavior

There is no icon, yet.

## Actions to Reproduce

![grafik](https://cloud.githubusercontent.com/assets/564768/25125808/6cc4a29e-2430-11e7-8b07-bc769f7042eb.png)

## Solution Description

We could use
- a regular expression icon (is there one?) or
- the CoderDojo Potsdam favicon https://github.com/CoderDojoPotsdam/organize/tree/master/logo

The favicon should also be used on the redirect pages.

## Hints

HTML pages can set the favicon with a tag in the head.

**Comment by hd719** [comment]
Hello I am new to open source can I work on this?

**Comment by niccokunzmann** [comment]
Hi, welcome! Yes, you can! Let me know if you need help or you like it more specific.

**Comment by Crizzooo** [comment]
I'll leave this one for @hd719, but got anything else for a first PR that you could need help with @niccokunzmann ?

**Comment by niccokunzmann** [comment]
@Crizzooo #7 is CSS only
#9 is putting a number into the current bubble one is working on, like in https://studio.code.org/s/mc/stage/1/puzzle/1 (Jekyll+CSS+HTML)
In #13 You can discuss with us what would be a good way to translate this into different languages and manage the different translations.
Let me know if you have any questions. You can also comment in the issues you are interested in.

**Comment by hd719** [comment]
Hey @niccokunzmann  so I think I added the favicon to all the pages, but how would I test it out? 

-Thank you.

**Comment by niccokunzmann** [comment]
@Crizzooo You can install [Jekyll](http://jekyllrb.com/) and run `jekyll serve --trace` to see the website at http://localhost:4000

If you like, you can add your learnings to a CONTRIBUTING.md file, so other have a quicker start.

Let me know it I can help you.

**Comment by hd719** [comment]
Alright cool i'll install Jekyll. 
Also @niccokunzmann  what do you mean by `learnings`?

**Comment by niccokunzmann** [comment]
`learnings` = Everything that could help other developers.

**Comment by niccokunzmann** [comment]
@hd719 The link is there but it does not show up.
![grafik](https://cloud.githubusercontent.com/assets/564768/25596612/4b430bca-2eca-11e7-8d85-a764307a5489.png)
I guess it is a path issue.
I will go to sleep now. Have a nice time, whereever you are :)

**Comment by hd719** [comment]
Try clearing your browser history.

**Comment by niccokunzmann** [comment]
Can you see the favicon here? https://github.com/CoderDojoPotsdam/regex-tutorial

**Comment by niccokunzmann** [comment]
I tried `../favicon.ico` and it is visible!

**Comment by niccokunzmann** [comment]
![grafik](https://cloud.githubusercontent.com/assets/564768/25609486/bf2b3954-2f1f-11e7-8442-0e25b772019f.png)

**Comment by hd719** [comment]
Hey @niccokunzmann I tried `../favicon.ico` and it worked for me as well do you want me to change it?
