### ISSUE TITLE
Change to next page when pressing enter (JavaScript)

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/regex-tutorial#20]
Website-link: https://coderdojopotsdam.github.io/regex-tutorial/steps/05-02-sets-with-ranges.html
This is an example. It concerns all pages with an input for a regular expression. See the source code for `class="playfield"`.

## Expected Behavior

When I solved the task, I would like to press enter to get to the next page.

## Actual Behavior

When I press enter, nothing happens.

## Actions to Reproduce

Solve the riddle, press enter, you are still on the same page.

## Solution Description

- JavaScript: Add a keypress test
- Jekyll: a form to switch to the next page

**Comment by orcutt989** [comment]
Link is not working. :-(

**Comment by niccokunzmann** [comment]
@orcutt989 Thanks! I corrected the link.

**Comment by weerox** [comment]
Check [this](https://weerox.github.io/regex-tutorial/steps/02-01-sequences-of-letters.html). 
It will send you to the next page when you press enter. Is this how you thought it would work?

**Comment by orcutt989** [comment]
Nice touch!

**Comment by niccokunzmann** [comment]
@WeeRox Yes, I mean that.
