### ISSUE TITLE
Make xkcd comic work offline (HTML)

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/regex-tutorial#22]
Website-link: https://coderdojopotsdam.github.io/regex-tutorial/steps/00-01-introduction.html

## Expected Behavior

I would like to see the xkcd image offline.

## Actual Behavior

I do not see the xkcd image offline

## Actions to Reproduce

go offline,
load generated page locally with jekyll

## Solution Description

- copy the image to the [extern folder](https://github.com/CoderDojoPotsdam/regex-tutorial/tree/master/extern) into a subfolder
- add a readme and license for the file

**Comment by orcutt989** [comment]
@niccokunzmann Do you want the whole regex tutorial offline with jekyll or literally just the image of the xkcd comic in the jekyll folder structure? I do not see an "extern" folder after creating a site in jekyll.

**Comment by niccokunzmann** [comment]
@orcutt989 The tutorial already works offline. This is the only image loaded from the internet. I added a link to the folder in the issue description. Could I answer your question?

**Comment by orcutt989** [comment]
@niccokunzmann danke schön. I will work on it and get back to you.

**Comment by niccokunzmann** [comment]
closed by #70
