### ISSUE TITLE
Translate examples

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/regex-tutorial#24]
Website-link: https://coderdojopotsdam.github.io/regex-tutorial/steps/03-03-or.html and more

## Expected Behavior

I expect the English tutorial to use English examples.

## Actual Behavior

Some of the examples given are stillin German.

## Solution Description

Find appropriate English examples.
The poem Ottos Mops has English equivalents.

**Comment by weerox** [comment]
I was looking at 03-01-or and saw earlier PRs and issues discussing this and whether we should use names of cities or use compound words instead, but never really understood what conclusion you came to

**Comment by weerox** [comment]
I decided to go with city names

**Comment by niccokunzmann** [comment]
As I see it, all English tutorial is English now. :)
