### ISSUE TITLE
make a menu to switch between languages

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/regex-tutorial#25]
Website-link: every step such as https://coderdojopotsdam.github.io/regex-tutorial/steps/03-03-or.html

## Expected Behavior

I would like to see a dropdown menu somewhere like with blockly games https://blockly-games.appspot.com/puzzle?lang=de

## Actual Behavior

The language can only be chosen by the first page

## Actions to Reproduce

go to the web site, in the footer you can not see the language menu

## Solution Description

Add a dropdown menu like with blockly to the bottom of the page.

## Hints

Please use the identifier such as 01-01 of the pages to find other translations.

**Comment by weerox** [comment]
What should we do if the user wan't to switch from the English version of 05-01 (for example) to the Swedish one, but it doesn't exist a Swedish translation? I was thinking about some sort of error page which tells you that the file isn't translated, but that the user can translate it if he/she wants to. To me that seems to be fairly easy to implement, but I don't now if we would be able to translate the error message. Any ideas?

**Comment by weerox** [comment]
I've been thinking of two ways to do this. 
1. You could include all languages that exists in the tutorial in a menu dropdown and alert the user if it tries to switch to a file which hasn't been translated yet. 
2. You could create a menu dropdown which only includes languages that the file exists in. 

The second approach might be more appealing, but the first might make users help translate the pages. 
What do you think @niccokunzmann?

**Comment by niccokunzmann** [comment]
I am ok with both and if this is not solved.

**Comment by niccokunzmann** [comment]
We now have a 404 page #83

**Comment by weerox** [comment]
Yeah, but I think I'll go with the second approach, it feels more dynamic and won't need as much maintenance.

**Comment by joshhazelhurst123** [comment]
@weerox I like option number 2. How about in the drop down box have a entry that say's 'add translation for tutorial' or something like that. When the user select's this option it goes to the error page which tells you that the file isn't translated, but that the user can translate it if he/she wants to.

**Comment by weerox** [comment]
@joshhazelhurst123 Or maybe we could redirect them to the README where there are instructions of how to translate?

**Comment by joshhazelhurst123** [comment]
@WeeRox I like that idea.

**Comment by DaricusDuncan** [comment]
Hi,
I am new to HTML, CSS, and JavaScript but I believe that I may have figured out how to create the drop-down menu and redirect the page using some HTML and JavaScript but I would like for someone to critique it for me if possible. How should I go about providing the code for review? @niccokunzmann

**Comment by weerox** [comment]
@DaricusDuncan Hi!
I guess that [this](https://github.com/DaricusDuncan/regex-tutorial_testing) is the repository where you have the code?

**Comment by niccokunzmann** [comment]
@DaricusDuncan You can provide your code as a pull request. Also, if you like feedback, you can share your progress or ideas here. If you like to show the changes to us on a live website, you can enable Github Pages in the settings for your repository and we can view the link.
Could I clarify some things? Would you like to ask more questions?

**Comment by DaricusDuncan** [comment]
@niccokunzmann Thank you so much for the help and suggestions. I will get the Github Pages enabled so that I can show the changes. That sounds like a great challenge to me. I believe that I will create a Github Pages as well as a PR for review. I am still working on it at the moment and testing the code out. Yes! @WeeRox that is indeed the area where I am working on my code under the WebOptions branch if you would like to take a look at it. I am open to all suggestions and criticism on the matter to make sure that I can doing my part to fix this issue at hand.

**Comment by niccokunzmann** [comment]
@DaricusDuncan If you like, you can also create a pull-request for this issue and add [WIP] to the title, "Work In Progress". This way, all other people know where to look, give suggestions and use your work. This speeds up the collaboration process.
If you have any questions, we are here:)

**Comment by DaricusDuncan** [comment]
@niccokunzmann  Just wanted to send out an update and say that I am still working on this. I have not forgotten or left it hanging. I will complete converting the JQuery to JavaScript.

**Comment by niccokunzmann** [comment]
Thanks for coming back:) Nice to hear from you and I wish you a nice
Christmas time!
You can register with 24pullrequests.com or depending on age find
students who like google code-in. It is currently running.

**Comment by DaricusDuncan** [comment]
Thank you as well! I got busy with work and family. I wish you a merry Christmas!! I have registered for 24pullrequest but have not been able to get 24 pull request done. Maybe over this upcoming weekend, I can knock out some of this work and reach some accomplishments. I am 26 so I cannot do the Google Code in. I actually was not aware of that project happening around this time.

**Comment by niccokunzmann** [comment]
I think, we have a menu to switch languages. Thanks! I will close this now.

**Comment by DaricusDuncan** [comment]
@niccokunzmann Thank you so much. I have the menu but I am having trouble getting rid of the JQuery the menu uses. I am still working on that issue. Been working on a project for my job but I am still active.
