### ISSUE TITLE
Proofread English Regular Expression tutorial

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/regex-tutorial#29]
I just translated [the English tutorial](https://coderdojopotsdam.github.io/regex-tutorial/). There must be mistakes in the tutorial.
Please proofread and if you find somthing that you would like to see improved,

- improve the page via the link at the bottom and submit a pull-requets.
- or, if you do do not like to improve it straigh away, create an issue

**Comment by CodeHeeler** [comment]
I am a first-timer and would like to do this!

**Comment by niccokunzmann** [comment]
@CodeHeeler Welcome! Please go ahead. You can let us know here, if you need help or do not know further.

**Comment by orcutt989** [comment]
@niccokunzmann I have some feedback having attempted to go through the tutorial in English, but if @CodeHeeler has it under control I won't worry about it.

**Comment by niccokunzmann** [comment]
@orcutt989 I think, you can submit your feedback. It is open and collaborative. I do not think, you are taking away by giving.

**Comment by orcutt989** [comment]
@niccokunzmann I can create an issue, but I think generally all the changes should be related to this issue, correct? Did you want an issue for each change? That sounds messy for you.

**Comment by niccokunzmann** [comment]
@orcutt989 @CodeHeeler Thanks for your feedback. I updated the description. You can directly edit the page and submit a pull-request. I did not clearly formulate this and wondered about the new issues^^

![grafik](https://cloud.githubusercontent.com/assets/564768/25964711/1171337c-3686-11e7-9700-e50a8ec84ee2.png)

**Comment by CodeHeeler** [comment]
Absolutely, the more, the merrier!

Also, I apologize for misunderstanding--I was not editing the text directly here through the "improve" link, I was coding on my own branch for later, including the "Next Step" buttons and other text in the JS and CSS files that you have since changed yourself.  I suppose the lesson is that when contributing, pull much more frequently.  Thanks again for letting me help!

**Comment by niccokunzmann** [comment]
Thanks for all the proof reads. Closing this, then. @orcutt989 @CodeHeeler
