### ISSUE TITLE
Style the index.html file

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/regex-tutorial#32]
Website-link: https://coderdojopotsdam.github.io/regex-tutorial/steps/index.html

## Expected Behavior

 Would like the page to be styled somehow.

## Actual Behavior

The page has small font maybe it is unreadable by people.

## Solution Description

- [ ] Add css to the page.
- [ ] make sure it works on the phone and on a desktop

## Hints

- add the css to the css folder
- if you like, you can include flags - make sure the license is ok.

**Comment by weerox** [comment]
What do you think about [these](https://dribbble.com/shots/1211759-Free-195-Flat-Flags) flags?

**Comment by niccokunzmann** [comment]
They look good.

**Comment by alikahwaji** [comment]
Hi, just a quick note I'm working on the styling  maybe in a couple of hours I have your PR ready.

**Comment by niccokunzmann** [comment]
I should be able to give feedback for your PR in about 8 hours from now as I will sleep soon.

**Comment by niccokunzmann** [comment]
@alikahwaji Created PR #102 I think, we can close this. If not, we should open a new issue to describe which other changes the index file needs.
