### ISSUE TITLE
Translate 03-02-or.html

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/regex-tutorial#37]
Website-link: https://coderdojopotsdam.github.io/regex-tutorial/steps/03-01-or.html and https://coderdojopotsdam.github.io/regex-tutorial/steps/03-02-or.html

## Expected Behavior

I would like to see English examples.

## Actual Behavior

I see German examples.

## Solution Description

- [ ] I would say, we can use English cities.
  - Nottingham
  - Birmingham
  - New York
  - New Orleans
  - London
  - ...

- [ ] Explain that we try to find all cities with a pattern, e.g. on a wikipedia site with all big cities.

What do you think?
One could look for "ham" and "New"

## Hints

Related: #35

**Comment by niccokunzmann** [comment]
See also https://github.com/CoderDojoPotsdam/regex-tutorial/pull/35#issuecomment-300884707

**Comment by orcutt989** [comment]
@niccokunzmann The easiest thing to do would be to just add the words "find bach, roda, and hausen", but right now this test is dependent on localization and English literacy. I think that the only requirement for this tutorial should be English literacy, not necesarilly localization. Its possible that there are English speakers that would not be familiar with those names as well.

I would suggest chagning the test from city names to compound words instead. For example...
```
Find words that contain the words "any" or "battle" or "dog".

anybody
doghouse
anyhow
cookbook
anyone
dogwood
anyplace
firsthand
battlecruiser
battleship
grapevine
battlecry
```
This way you dont have to worry about the reader's competency of where they live, but instead their English comptetency which is the point of the English tutorial.

**Comment by niccokunzmann** [comment]
#40 closes this
