### ISSUE TITLE
Translate 99-01-muellhalde to English

### ISSUE THREAD

**Issue by weerox** [CoderDojoPotsdam/regex-tutorial#57]
Website-link: 
https://coderdojopotsdam.github.io/regex-tutorial/steps/99-01-muellhalde.html

The page only exists in German and should probably be translated to English as well.

**Comment by niccokunzmann** [comment]
This page contains an other idea: use brackets to extract parts of the regular expression. On this page: extract the image http link from the img tag.

    regex: a(b)c
    text: abc
    result: {"all": "abc", 0: "b"}

I am not sure how to introduce this.
Maybe, I should remove it from the German status so people do not wonder what is the next step.
What do you think?

**Comment by niccokunzmann** [comment]
I will remove this file and we can start a new issue about which parts of the regular expressions should be added.
