### ISSUE TITLE
Fix the navigation "step bubbles"

### ISSUE THREAD

**Issue by weerox** [CoderDojoPotsdam/regex-tutorial#78]
## Expected Behavior

The step "bubbles" should be closer to each other. 
## Actual Behavior

They are pretty far away. 

For some reason it broke when I changed the way we make translations. Can't find the reason myself, maybe someone else will.

**Comment by niccokunzmann** [comment]
You removed the comments. Now, there are spaces behind the elements. If there are no spaces between the elements, this works or, maybe there is a possibility to reduce the width of the space to zero.

Before:

     </div><div

Now:

       </div>
           <div

**Comment by niccokunzmann** [comment]
#79 does not resolve this.
![grafik](https://user-images.githubusercontent.com/564768/28485819-88e52ebc-6e7c-11e7-8c35-087978778ed4.png)

**Comment by weerox** [comment]
Fixed by #80
