### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/regex-tutorial#83]
Website-link: https://duckduckgo.com/?q=interaktives+tutorial+regul%C3%A4re+ausdr%C3%BCcke&t=ffab&ia=software
and https://coderdojopotsdam.github.io/regex-tutorial/steps/00-01-einfuehrung.html

## Expected Behavior

I would like to see the something useful when I get to pages which moved.

## Actual Behavior

I only see the Github 404 page.

## Actions to Reproduce

Click the link https://coderdojopotsdam.github.io/regex-tutorial/steps/00-01-einfuehrung.html
Please let me know if you like to work on this.

## Solution Description

Jekyll supports 404 pages. The 404 page should contain a useful description for the tutorial

## Hints

The 404 page could redirect to the language overview page

**Comment by joshhazelhurst123** [comment]
Hi, I would like to a look at this one. I am a little confused however. This link works https://coderdojopotsdam.github.io/regex-tutorial/en/00-01.html
I had to modify what you originally have.
https://coderdojopotsdam.github.io/regex-tutorial/steps/00-01-einfuehrung.html
Is there something I am missing here? Seems like it works fine.

**Comment by niccokunzmann** [comment]
The problem I see is that the tutorial files get renamed from time to time and older links do not work any more. Normal users can not handle a situation with a 404 page like this:
![grafik](https://user-images.githubusercontent.com/564768/28497144-0e0a4d58-6f80-11e7-9587-f74bd457d4a6.png)

So, the 404 page should give some guidance to those who can not manipulate the urls. 

The 404 page contains 

- at least
  - a link or a redirect to the tutorial start page
- maybe 
  - an explanation that the file was renamed and you can find it in the tutorial 
  - a link to the github search for the file if you really must look at exactly this file

That were my thoughts. What do you think?

**Comment by joshhazelhurst123** [comment]
I understand now that by putting a 404.html file into the root directory Jekyll will handle the file, with the tags below in the 404.html (first-timers-only here). 
1 --- 
2 layout: page
3 permalink: /404.html 
4 --- 
A redirect link to the tutorial start page is a good idea. 
I think what you have added into the maybe description is a good idea also. I'm not sure how you want to format this page, if you want something amazing. I was thinking something pretty simple.

**Comment by niccokunzmann** [comment]
Sure, you can style it very simply. Very simple, unstyled HTML is an improvement. Besides, this site will be looked at seldomly.

**Comment by niccokunzmann** [comment]
#87 closes this. Thanks @joshhazelhurst123
