### ISSUE TITLE
Make the number of the step visible

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojoPotsdam/regex-tutorial#9]
Um Feedback gut zuzuordnen, wäre es gut, den Schritt irgendwo anzuzeigen.

- Code.org hat die Zahl des Schrittes in den kleinen Kreisen für den Fortschritt
- Man kann den Schritt in den Footer/Header/Überschrift tun

**Comment by Crizzooo** [comment]
@niccokunzmann Can  I get a translation here?

**Comment by niccokunzmann** [comment]
In order to give feedback, it would be good to see the number of the step.

- [Code-org](https://studio.code.org/s/mc/stage/1/puzzle/1) puts the number into the step bubble
- one could put the step into the footer/header/heading

**Comment by niccokunzmann** [comment]
@Crizzooo You can discuss it if you are not sure but you can also create a pull-Request with what you think works best.

**Comment by weerox** [comment]
@niccokunzmann Is there a reason that we use two integers for the topic and the step? Could we change it from 05-01 to 5-1? That would make it easier to add the number into the bubble, because I couldn't find a way to remove the leading zero using Jekyll, but maybe I could use JavaScript.

**Comment by niccokunzmann** [comment]
I can find this way. You can go on, I will add it after merge.

**Comment by weerox** [comment]
I think that I'll try to solve it using JavaScript first
Edit: It was easy to fix it with JavaScript, so we can keep the zeros.

**Comment by niccokunzmann** [comment]
I would like the numbers to be increasing. Now, number 1 is there several times.

**Comment by weerox** [comment]
Oh, now I see what your code in #91 did. I thought that you wanted them numbered for each topic. I'll take another look

**Comment by niccokunzmann** [comment]
I should have translated this. Sorry.

**Comment by weerox** [comment]
You did translate it, it's just that code.org didn't have multiple "topics" so that's why I misunderstood.
